---
title: "Datathon_Project"
author: "Samira Nassi"
date: "2/20/2025"
output: pdf_document
---

```{r}
# Importing the TRAIN dataset---------------------------------------------------------------------------------------------------------------------
library(readxl)
setwd("C:/Users/nassi/OneDrive/Documents/ISTA_321/widsdatathon2025/TRAIN_NEW")
quantitative <- read_excel("TRAIN_QUANTITATIVE_METADATA_new.xlsx")
categorical <- read_excel("TRAIN_CATEGORICAL_METADATA_new.xlsx")
solution <- read_excel("TRAINING_SOLUTIONS.xlsx")
connectome <- read.csv("TRAIN_FUNCTIONAL_CONNECTOME_MATRICES_new_36P_Pearson.csv")
```

```{r}
# Checking if there are any NA's
sum(is.na(quantitative))
sum(is.na(categorical))
sum(is.na(connectome))
sum(is.na(solution))

# Imputating the NA values
quant <- quantitative
for (i in 1:ncol(quant)) {
  if(is.numeric(quant[[i]])){
    quant[[i]][is.na(quant[[i]])] <- mean(quant[[i]], na.rm = TRUE)
  }
}
sum(is.na(quant))

cat <- categorical 
for (i in 1:ncol(cat)){
  if(is.numeric(cat[[i]])){
    cat[[i]][is.na(cat[[i]])] <- mean(cat[[i]], na.rm = TRUE)
  }
}
sum(is.na(cat))
```

```{r}
# Merging the train dataset
library(tidyverse)

merged_data <- inner_join(quant, cat, by = "participant_id")
all_data <- inner_join(merged_data, solution, by = "participant_id")
```

```{r}
library(dplyr)
# PCA to reduce dimensionality on the connectome
matrix_only <- connectome %>%
  select(where(is.numeric))

matrix_scaled <- scale(matrix_only)

pca_result <- prcomp(matrix_scaled, center = TRUE, scale. = TRUE)
```

```{r}
# Extracting the the eigenvalues from the PCA object
eigenvalues <- pca_result$sdev^2

# Count eigenvalues less than 1
sum(eigenvalues < 1)

# Create a scree plot
plot(eigenvalues, type = "b",
     xlab = "Principal Component",
     ylab = "Eigenvalue")

# Add a line at y = 1 to indicate the elbow
abline(h = 1, col = "red")

# Looking at the graph I chose 50 as the elbow point
connectome_pca <- as.data.frame(pca_result$x[,1:50])
```

```{r}
# Merging the pca connectome to all of the whole train dataset
final_dataset <- bind_cols(all_data %>%
                             select(ADHD_Outcome, Sex_F, everything()), connectome_pca)
head(final_dataset)
```

```{r}
library(caret)
# Removing non-predictive IDs
data_model <- final_dataset %>% select(-participant_id)

# Defining targets
targets <- data_model %>% select(ADHD_Outcome, Sex_F)

predictors <- data_model %>% select(-ADHD_Outcome, -Sex_F)

# Train/test split (80/20)
set.seed(123)
train_index <- createDataPartition(targets$ADHD_Outcome, p = 0.8, list = FALSE)

X_train <- predictors[train_index, ]
X_test <- predictors[-train_index, ]
Y_train <- targets[train_index, ]
Y_test <- targets[-train_index, ]
```

```{r}
library("randomForest")

#ADHD Output model
rf_adhd <- randomForest(x = X_train, y = as.factor(Y_train$ADHD_Outcome), ntree = 500)

#Sex Model
rf_sex <- randomForest(x = X_train, y = as.factor(Y_train$Sex_F), ntree = 500)

#Evaluate Models
adhd_preds <- predict(rf_adhd, X_test, type = "prob")[, 2]
#adhd_auc <- AUC(adhd_preds, Y_test$ADHD_Outcome) # Need to find library for AUC

sex_preds <- predict(rf_sex, X_test, type = "prob")[, 2]
#sex_auc <- AUC(sex_preds, Y_test$Sex_F)

importance(rf_adhd) %>% as.data.frame() %>% arrange(desc(MeanDecreaseGini)) %>% head(10)
importance(rf_sex) %>% as.data.frame() %>% arrange(desc(MeanDecreaseGini)) %>% head(10)
```

```{r}
# Importing the TEST dataset----------------------------------------------------------------------------------------------------------------------
setwd("C:/Users/nassi/OneDrive/Documents/ISTA_321/widsdatathon2025/TEST")

test_quantitative <- read_excel("TEST_QUANTITATIVE_METADATA.xlsx")
test_categorical <- read_excel("TEST_CATEGORICAL.xlsx")
test_connectome <- read.csv("TEST_FUNCTIONAL_CONNECTOME_MATRICES.csv")
```

```{r}
# Checking if there are any NA's
sum(is.na(test_quantitative))
sum(is.na(test_categorical))
sum(is.na(test_connectome))

# Imputating the NA values
test_quant <- test_quantitative
for (i in 1:ncol(test_quant)) {
  if(is.numeric(test_quant[[i]])){
    test_quant[[i]][is.na(test_quant[[i]])] <- mean(test_quant[[i]], na.rm = TRUE)
  }
}
sum(is.na(test_quant))

test_cat <- test_categorical 
for (i in 1:ncol(test_cat)){
  if(is.numeric(test_cat[[i]])){
    test_cat[[i]][is.na(test_cat[[i]])] <- mean(test_cat[[i]], na.rm = TRUE)
  }
}
sum(is.na(test_cat))
```

```{r}
# PCA on test connectome
tmatrix_only <- test_connectome %>%
  select(where(is.numeric))

tmatrix_scaled <- scale(tmatrix_only)

test_pca_result <- prcomp(tmatrix_scaled, center = TRUE, scale. = TRUE)

test_connectome_pca <- as.data.frame(test_pca_result$x[,1:50])
head(test_connectome_pca)
```

```{r}
# Merging the test data
merged_test_data <- inner_join(test_quant, test_cat, by = "participant_id")
final_test_dataset <- cbind(merged_test_data, test_connectome_pca)
head(final_test_dataset)
```


```{r}
# Creating our predictions and output
predicted_adhd <- predict(rf_adhd, newdata = final_test_dataset, type = "class")
predicted_gender <- predict(rf_sex, newdata = final_test_dataset, type = "class")

participant_ids <- final_test_dataset$participant_id

output_df <- data.frame(
  participant_id = participant_ids,
  ADHD_Outcome = predicted_adhd,
  Sex_F = predicted_gender
)
print(output_df)

write.csv(output_df, "Submission_1.csv", row.names = FALSE)
```
